apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: manual
  namespace: openshift-performance-addon
spec:
  additionalKernelArgs:
    - "nmi_watchdog=0"
    - "audit=0"
    - "mce=off"
    - "processor.max_cstate=1"
    - "idle=poll"
    - "intel_idle.max_cstate=0"
  cpu:
    isolated: "2-23,26-47"
    reserved: "0,24,1,25"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
      - size: "1G"
        count: 32
        node: 0
      - size: "1G"
        count: 32
        node: 1
  numa:
    topologyPolicy: "single-numa-node"
  nodeSelector:
    node-role.kubernetes.io/worker: ""
