---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: sriov-device-plugin-vhost
  namespace: openshift-sriov-network-operator
  annotations:
    kubernetes.io/description: |
      This daemon set launches the SR-IOV network device plugin on each node.
spec:
  selector:
    matchLabels:
      app: sriov-device-plugin-vhost
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 33%
  template:
    metadata:
      annotations:
        target.workload.openshift.io/management: '{"effect": "PreferredDuringScheduling"}'
      labels:
        app: sriov-device-plugin-vhost
        component: network
        type: infra
        openshift.io/component: network
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: feature.node.kubernetes.io/network-vhostuser.capable
                operator: In
                values:
                - "true"
      hostNetwork: true
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/worker:
      tolerations:
      - operator: Exists
      serviceAccountName: sriov-device-plugin
      priorityClassName: "system-node-critical"
      containers:
      - name: sriov-device-plugin
        image: registry.redhat.io/openshift4/ose-sriov-network-device-plugin@sha256:a76585896ddd70b53a261cf63f05a7288af3dd3ff93468d97dbe34c91e5811eb
        args:
        - --log-level=10
        - --resource-prefix=openshift.io
        - --config-file=/etc/pcidp/vhost.json
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        volumeMounts:
        - name: devicesock
          mountPath: /var/lib/kubelet/
          readOnly: false
        - name: config-volume
          mountPath: /etc/pcidp/
          readOnly: true
        - name: device-info
          mountPath: /var/run/k8s.cni.cncf.io/devinfo/dp
      volumes:
        - name: devicesock
          hostPath:
            path: /var/lib/kubelet/
        - name: net
          hostPath:
            path: /sys/class/net
        - name: config-volume
          hostPath:
            path: /var/lib/vhostuser/
            type: DirectoryOrCreate
        - name: device-info
          hostPath:
            path: /var/run/k8s.cni.cncf.io/devinfo/dp
            type: DirectoryOrCreate
