#!/usr/bin/env python

import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-n', '--name', default='bmh-secret',
            help='Name of the secret')
    parser.add_argument('-u', '--user', default='root',
            help='IPMI Username')
    parser.add_argument('-p', help='IPMI Password')
    args = parser.parse_args()

    with open(item) as f:
        obj = yaml.safe_load(f)




if __name__ == "__main__":
    main()
