#!/usr/bin/env python

import argparse
import base64
import jinja2
import os

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--cluster-name", help="Cluster Name (dir under ./cluster/)", required=True)
    parser.add_argument('-n', '--name', default='bmh-secret',
            help='Name of the secret')
    parser.add_argument('-u', '--username', default='root',
            help='IPMI Username')
    parser.add_argument('-p', '--password', help='IPMI Password')
    args = parser.parse_args()

    bmh_tmpl_path = os.path.join(os.path.dirname(__file__), '../templates', 'bmh-secret.yaml.j2')
    with open(bmh_tmpl_path) as f:
        template = jinja2.Template(f.read())
    username = base64.b64encode(str.encode(args.username)).decode()
    password = base64.b64encode(str.encode(args.password)).decode()
    data = template.render(username=username, password=password, name=args.name)

    bmh_file_dir = os.path.join(os.path.dirname(__file__), '../cluster', args.cluster_name)
    if not os.path.exists(bmh_file_dir):
        os.makedirs(bmh_file_dir)
    bmh_file_path = os.path.join(bmh_file_dir, 'bmh-secret.yaml')
    with open(bmh_file_path, 'w') as f:
        f.write(data)



if __name__ == "__main__":
    main()
