#!/usr/bin/env python

import argparse
import base64
import jinja2
import os

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-n', '--name', default='bmh-secret',
            help='Name of the secret')
    parser.add_argument('-u', '--username', default='root',
            help='IPMI Username')
    parser.add_argument('-p', '--password', help='IPMI Password')
    parser.add_argument('-m', '--mac', help='PXE Mac address')
    parser.add_argument('-i', '--ip', help='IPMI IP Address')
    args = parser.parse_args()

    bmh_tmpl_path = os.path.join(os.path.dirname(__file__), '../templates', 'bmh.yaml.j2')
    with open(bmh_tmpl_path) as f:
        template = jinja2.Template(f.read())
    username = base64.b64encode(str.encode(args.username)).decode()
    password = base64.b64encode(str.encode(args.password)).decode()
    data = template.render(username=username, password=password, name=args.name, mac=args.mac, bmc_ip=args.ip)

    bmh_file_path = os.path.join(os.path.expanduser("~"), args.name + '.yaml')
    with open(bmh_file_path, 'w') as f:
        f.write(data)



if __name__ == "__main__":
    main()
