apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: cnf-basic-profile
  namespace: openshift-performance-addon
spec:
  additionalKernelArgs:
    - "nmi_watchdog=0"
    - "audit=0"
    - "mce=off"
    - "processor.max_cstate=1"
    - "idle=poll"
    - "intel_idle.max_cstate=0"
  cpu:
    isolated: "2-11,14-23"
    reserved: "0,12,1,13"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
      - size: "1G"
        count: 32
        node: 0
  numa:
    topologyPolicy: "best-effort"
  nodeSelector:
    node-role.kubernetes.io/worker: ""
